$kind: http-example
request:
  url: "{{baseUrl}}/config/api/v1/bookmarks/:bookmarkId"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    bookmarkId: ""
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "id": "<string>",
        "path": "<string>",
        "title": "<string>",
        "icon": "<string>",
        "isFilterBookmark": "<boolean>",
        "visibleToGroups": [
          "<string>",
          "<string>"
        ]
      }
order: 1000
