$kind: http-example
request:
  url: "{{baseUrl}}/providers/:providerName/config"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    providerName: ""
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "code": "<string>",
        "message": "<string>"
      }
order: 2000
