$kind: http-example
request:
  url: "{{baseUrl}}/config/api/v1/bookmarks"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      [
        {
          "path": "<string>",
          "title": "<string>",
          "icon": "<string>",
          "isFilterBookmark": "<boolean>",
          "visibleToGroups": [
            "<string>",
            "<string>"
          ]
        },
        {
          "path": "<string>",
          "title": "<string>",
          "icon": "<string>",
          "isFilterBookmark": "<boolean>",
          "visibleToGroups": [
            "<string>",
            "<string>"
          ]
        }
      ]
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      [
        {
          "id": "<string>",
          "path": "<string>",
          "title": "<string>",
          "icon": "<string>",
          "isFilterBookmark": "<boolean>",
          "visibleToGroups": [
            "<string>",
            "<string>"
          ]
        },
        {
          "id": "<string>",
          "path": "<string>",
          "title": "<string>",
          "icon": "<string>",
          "isFilterBookmark": "<boolean>",
          "visibleToGroups": [
            "<string>",
            "<string>"
          ]
        }
      ]
order: 1000
