$kind: http-example
name: Tenant Config was retrieved.
request:
  url: "{{baseUrl}}/config/api/v1/config"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: "{}"
order: 1000
