$kind: http-example
request:
  url: "{{baseUrl}}/config/automation"
  method: PUT
  headers:
    Content-Type: application/json
  body:
    type: json
    content: "{}"
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
