$kind: http-example
name: User settings was updated.
request:
  url: "{{baseUrl}}/auxiliary/api/v1/userSettings"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "bookmarks": [
          {
            "icon": "<string>",
            "title": "<string>",
            "path": "<string>",
            "folderId": "<string>",
            "isFilterBookmark": "<boolean>",
            "itemId": "<string>"
          },
          {
            "icon": "<string>",
            "title": "<string>",
            "path": "<string>",
            "folderId": "<string>",
            "isFilterBookmark": "<boolean>",
            "itemId": "<string>"
          }
        ],
        "workFolderId": "<uuid>",
        "lastSeenChangelogId": "<uuid>",
        "defaultFilters": [
          {
            "isExactSearch": "<boolean>",
            "token": "<string>",
            "value": "<string>",
            "isRecognized": "<boolean>",
            "isSticky": "<boolean>",
            "filterKey": "<string>"
          },
          {
            "isExactSearch": "<boolean>",
            "token": "<string>",
            "value": "<string>",
            "isRecognized": "<boolean>",
            "isSticky": "<boolean>",
            "filterKey": "<string>"
          }
        ],
        "dismissedNotifications": {
          "fugiat_85f": {
            "code": "<string>",
            "text": "<boolean>"
          }
        },
        "showRenameSubclipDialog": "<boolean>"
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "bookmarks": [
          {
            "icon": "<string>",
            "title": "<string>",
            "path": "<string>",
            "folderId": "<string>",
            "isFilterBookmark": "<boolean>",
            "itemId": "<string>"
          },
          {
            "icon": "<string>",
            "title": "<string>",
            "path": "<string>",
            "folderId": "<string>",
            "isFilterBookmark": "<boolean>",
            "itemId": "<string>"
          }
        ],
        "workFolderId": "<uuid>",
        "lastSeenChangelogId": "<uuid>",
        "defaultFilters": [
          {
            "isExactSearch": "<boolean>",
            "token": "<string>",
            "value": "<string>",
            "isRecognized": "<boolean>",
            "isSticky": "<boolean>",
            "filterKey": "<string>"
          },
          {
            "isExactSearch": "<boolean>",
            "token": "<string>",
            "value": "<string>",
            "isRecognized": "<boolean>",
            "isSticky": "<boolean>",
            "filterKey": "<string>"
          }
        ],
        "dismissedNotifications": {
          "fugiat_85f": {
            "code": "<string>",
            "text": "<boolean>"
          }
        },
        "showRenameSubclipDialog": "<boolean>"
      }
order: 1000
