$kind: http-request
description: |
  Get tenant configuration information
url: "{{baseUrl}}/config/api/v1/config"
method: GET
headers:
  Accept: application/json
examples: ./.resources/Get tenant configuration information.resources/examples
order: 4000
