$kind: http-example
request:
  url: "{{baseUrl}}/config/api/v1/bookmarks/:bookmarkId"
  method: DELETE
  headers:
    Accept: application/json
  pathVariables:
    bookmarkId: ""
response:
  statusCode: 404
  statusText: Not Found
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "statusCode": "<integer>",
        "message": "<string>",
        "developerMessage": "<string>"
      }
order: 5000
