$kind: http-example
request:
  url: "{{baseUrl}}/prime/api/v1/replication"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "modified": {
          "on": "<dateTime>",
          "by": "<string>"
        },
        "sources": [
          {
            "stage": "prod-syd",
            "after": "<dateTime>",
            "externallyReplicatedStorages": [
              {
                "source": "<string>",
                "target": "<string>"
              },
              {
                "source": "<string>",
                "target": "<string>"
              }
            ],
            "shardCount": "<integer>"
          },
          {
            "stage": "apac",
            "after": "<dateTime>",
            "externallyReplicatedStorages": [
              {
                "source": "<string>",
                "target": "<string>"
              },
              {
                "source": "<string>",
                "target": "<string>"
              }
            ],
            "shardCount": "<integer>"
          }
        ]
      }
order: 1000
