$kind: http-example
request:
  url: "{{baseUrl}}/prime/api/v1/replication"
  method: PUT
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "sources": [
          {
            "stage": "apac",
            "after": "<dateTime>",
            "externallyReplicatedStorages": [
              {
                "source": "<string>",
                "target": "<string>"
              },
              {
                "source": "<string>",
                "target": "<string>"
              }
            ],
            "secretMimirApiToken": "<string>",
            "shardCount": "<integer>"
          },
          {
            "stage": "prod",
            "after": "<dateTime>",
            "externallyReplicatedStorages": [
              {
                "source": "<string>",
                "target": "<string>"
              },
              {
                "source": "<string>",
                "target": "<string>"
              }
            ],
            "secretMimirApiToken": "<string>",
            "shardCount": "<integer>"
          }
        ]
      }
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
